from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status

from studio_api.dependencies import get_store
from studio_api.openapi import CONFLICT_RESPONSE, PROJECT_NOT_FOUND_RESPONSE
from studio_api.storage import JsonStore
from studio_schemas import (
    ActivityEvent,
    ActivityEventType,
    CreateEvidenceRequest,
    CreateEvidenceResponse,
    CreateResearchProjectRequest,
    DecisionProposal,
    Evidence,
    EvidenceCitation,
    InvestmentDecision,
    ProjectStatus,
    ResearchArtifact,
    ResearchProject,
    ResearchTask,
    ResearchWorkflowResponse,
    Thesis,
    new_id,
)
from studio_workflows import WorkflowError, plan_tasks, run_research_workflow

router = APIRouter(prefix="/research-projects", tags=["research-projects"])
StoreDep = Annotated[JsonStore, Depends(get_store)]


def project_title(topic: str) -> str:
    topic = topic.strip()
    if len(topic) <= 72:
        return topic
    return f"{topic[:69].rstrip()}..."


@router.post(
    "",
    response_model=ResearchProject,
    status_code=status.HTTP_201_CREATED,
    summary="Create a research project",
    description=(
        "Create a project from a free-form investment topic and immediately seed the fixed MVP research tasks. "
        "This records project-created and task-created activity events."
    ),
    response_description="The created research project.",
)
def create_project(request: CreateResearchProjectRequest, store: StoreDep) -> ResearchProject:
    project = store.create(
        "projects",
        ResearchProject(
            title=project_title(request.topic),
            topic=request.topic,
            objective=f"Assess investable implications of: {request.topic}",
            status=ProjectStatus.CREATED,
        ),
    )
    store.create(
        "activity_events",
        ActivityEvent(project_id=project.id, event_type=ActivityEventType.PROJECT_CREATED, message="Created research project."),
    )
    for task in plan_tasks(project):
        store.create("tasks", task)
        store.create(
            "activity_events",
            ActivityEvent(project_id=project.id, task_id=task.id, event_type=ActivityEventType.TASK_CREATED, message=f"Created {task.desk.value} desk task."),
        )
    return project


@router.get(
    "",
    response_model=list[ResearchProject],
    summary="List research projects",
    description="Return all persisted research projects in local storage.",
    response_description="Research projects visible to the current local Studio instance.",
)
def list_projects(store: StoreDep) -> list[ResearchProject]:
    return store.list("projects")


@router.get(
    "/{project_id}",
    response_model=ResearchProject,
    summary="Get a research project",
    description="Return one research project by ID.",
    response_description="The requested research project.",
    responses=PROJECT_NOT_FOUND_RESPONSE,
)
def get_project(project_id: str, store: StoreDep) -> ResearchProject:
    return _get_project_or_404(store, project_id)


@router.get(
    "/{project_id}/tasks",
    response_model=list[ResearchTask],
    summary="List project research tasks",
    description="Return the desk tasks planned for a project, including their desk assignment and workflow status.",
    response_description="Research tasks for the project.",
    responses=PROJECT_NOT_FOUND_RESPONSE,
)
def list_project_tasks(project_id: str, store: StoreDep) -> list[ResearchTask]:
    _get_project_or_404(store, project_id)
    return [task for task in store.list("tasks") if task.project_id == project_id]


@router.get(
    "/{project_id}/activity-events",
    response_model=list[ActivityEvent],
    summary="List project activity events",
    description="Return the project timeline used by the UI to explain workflow progress and state changes.",
    response_description="Activity events for the project.",
    responses=PROJECT_NOT_FOUND_RESPONSE,
)
def list_project_activity_events(project_id: str, store: StoreDep) -> list[ActivityEvent]:
    _get_project_or_404(store, project_id)
    return [event for event in store.list("activity_events") if event.project_id == project_id]


@router.get(
    "/{project_id}/artifacts",
    response_model=list[ResearchArtifact],
    summary="List project research artifacts",
    description="Return cited research artifacts generated by completed research tasks.",
    response_description="Research artifacts for the project.",
    responses=PROJECT_NOT_FOUND_RESPONSE,
)
def list_project_artifacts(project_id: str, store: StoreDep) -> list[ResearchArtifact]:
    _get_project_or_404(store, project_id)
    return [artifact for artifact in store.list("artifacts") if artifact.project_id == project_id]


@router.get(
    "/{project_id}/decision-proposals",
    response_model=list[DecisionProposal],
    summary="List project decision proposals",
    description="Return committee proposals linked to the project. Proposals remain separate from user decisions.",
    response_description="Decision proposals for the project.",
    responses=PROJECT_NOT_FOUND_RESPONSE,
)
def list_project_decision_proposals(project_id: str, store: StoreDep) -> list[DecisionProposal]:
    _get_project_or_404(store, project_id)
    return [proposal for proposal in store.list("proposals") if proposal.project_id == project_id]


@router.get(
    "/{project_id}/investment-decisions",
    response_model=list[InvestmentDecision],
    summary="List project investment decisions",
    description="Return user approve/reject decision records linked to this project.",
    response_description="Investment decisions for the project.",
    responses=PROJECT_NOT_FOUND_RESPONSE,
)
def list_project_investment_decisions(project_id: str, store: StoreDep) -> list[InvestmentDecision]:
    _get_project_or_404(store, project_id)
    return [decision for decision in store.list("decisions") if decision.project_id == project_id]


@router.get(
    "/{project_id}/thesis",
    response_model=Thesis,
    summary="Get latest project thesis",
    description="Return the latest thesis version for a project after the workflow has produced one.",
    response_description="The latest project thesis.",
    responses=PROJECT_NOT_FOUND_RESPONSE,
)
def get_project_thesis(project_id: str, store: StoreDep) -> Thesis:
    _get_project_or_404(store, project_id)
    theses = [thesis for thesis in store.list("theses") if thesis.project_id == project_id]
    if not theses:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Thesis not found.")
    return sorted(theses, key=lambda thesis: thesis.version)[-1]


@router.get(
    "/{project_id}/evidence",
    response_model=list[Evidence],
    summary="List project evidence",
    description="Return evidence records attached to the project, including user-provided notes/articles and fixture fallback evidence.",
    response_description="Evidence records for the project.",
    responses=PROJECT_NOT_FOUND_RESPONSE,
)
def list_project_evidence(project_id: str, store: StoreDep) -> list[Evidence]:
    _get_project_or_404(store, project_id)
    return [item for item in store.list("evidence") if item.project_id == project_id]


@router.post(
    "/{project_id}/evidence",
    response_model=CreateEvidenceResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Attach user evidence",
    description=(
        "Attach a user-provided note or article to a project with at least one citation excerpt. "
        "These citations can replace curated fixture evidence for the matching research desk."
    ),
    response_description="The created evidence record and its citation records.",
    responses={**PROJECT_NOT_FOUND_RESPONSE, **CONFLICT_RESPONSE},
)
def create_project_evidence(project_id: str, request: CreateEvidenceRequest, store: StoreDep) -> CreateEvidenceResponse:
    project = _get_project_or_404(store, project_id)
    project_citations = _project_citations(store, project.id)

    evidence = Evidence(
        id=new_id("evidence"),
        project_id=project.id,
        source_type=request.source_type,
        title=request.title,
        url=request.url,
        summary=request.summary,
        metadata={"desk": request.desk.value, "origin": "user"},
    )
    citations = [
        EvidenceCitation(
            id=new_id("citation"),
            evidence_id=evidence.id,
            label=citation.label or f"USER-{len(project_citations) + index}",
            excerpt=citation.excerpt,
            location=citation.location,
        )
        for index, citation in enumerate(request.citations, start=1)
    ]

    try:
        evidence = store.create("evidence", evidence)
        citations = [store.create("citations", citation) for citation in citations]
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(exc)) from exc

    store.create(
        "activity_events",
        ActivityEvent(project_id=project.id, event_type=ActivityEventType.EVIDENCE_ATTACHED, message=f"Added user evidence for {request.desk.value} desk."),
    )
    return CreateEvidenceResponse(evidence=evidence, citations=citations)


@router.get(
    "/{project_id}/citations",
    response_model=list[EvidenceCitation],
    summary="List project citations",
    description="Return citation excerpts that resolve to evidence owned by this project.",
    response_description="Citation records for project-owned evidence.",
    responses=PROJECT_NOT_FOUND_RESPONSE,
)
def list_project_citations(project_id: str, store: StoreDep) -> list[EvidenceCitation]:
    _get_project_or_404(store, project_id)
    return _project_citations(store, project_id)


@router.post(
    "/{project_id}/run-research",
    response_model=ResearchWorkflowResponse,
    summary="Run deterministic research workflow",
    description=(
        "Run the local deterministic research workflow for a project. The runner completes fixed desk tasks, "
        "selects user evidence or SMR fallback fixtures, generates cited artifacts, and synthesizes a thesis."
    ),
    response_description="The workflow result, including project, tasks, evidence, citations, artifacts, thesis, and activity events.",
    responses={**PROJECT_NOT_FOUND_RESPONSE, **CONFLICT_RESPONSE},
)
def run_project_research_workflow(project_id: str, store: StoreDep) -> ResearchWorkflowResponse:
    try:
        result = run_research_workflow(store, project_id)
    except KeyError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Project not found.") from exc
    except WorkflowError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(exc)) from exc

    return ResearchWorkflowResponse(
        project=result.project,
        tasks=result.tasks,
        evidence=result.evidence,
        citations=result.citations,
        artifacts=result.artifacts,
        thesis=result.thesis,
        activity_events=result.activity_events,
    )


def _get_project_or_404(store: JsonStore, project_id: str) -> ResearchProject:
    project = store.get("projects", project_id)
    if project is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Project not found.")
    return project


def _project_citations(store: JsonStore, project_id: str) -> list[EvidenceCitation]:
    evidence_ids = {item.id for item in store.list("evidence") if item.project_id == project_id}
    return [citation for citation in store.list("citations") if citation.evidence_id in evidence_ids]
